<?php return array (
  0 => 
  array (
    'id' => 5500,
    'typeId' => '11',
    'type' => 2,
    'subject' => '彭某驾驶一辆重型半挂牵引车，载运37.7吨货物（核载25吨），行至大广高速公路一下坡路段，追尾碰撞一辆由李某驾驶在应急车道内行驶的重型自卸货车（货箱内装载3.17立方黄土并搭乘24人），造成16人死亡、13人受伤.此事故中的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '彭某超速行驶',
    'optionB' => '彭某驾驶机动车超载',
    'optionC' => '李某在应急车道内行驶',
    'optionD' => '李某货车车厢内违法载人',
    'answer' => '2,3,4',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、载运37.7吨货物（核载25吨），说明超载；2、李某驾驶在应急车道内行驶，说明李某违法在应急车道行驶，应急车道只能应急使用；3、货箱内装载3.17立方黄土并搭乘24人，货车不能拉人。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  1 => 
  array (
    'id' => 5501,
    'typeId' => '11',
    'type' => 2,
    'subject' => '戚某驾驶大客车，乘载28人（核载55人），由南向北行至一无交通信号控制的交叉路口，以50公里的时速与由东向西行至该路口李某驾驶的重型半挂牵引车（核载40吨，实载55.2吨）侧面相撞，造成12人死亡、17人受伤.此事故中的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '客车超员',
    'optionB' => '客车超速行驶',
    'optionC' => '货车超载',
    'optionD' => '货车驾驶人经验不足',
    'answer' => '2,3',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、交叉路口以50km/h,属于超速；2、核载40吨，实载55.2吨，属于超载。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  2 => 
  array (
    'id' => 5502,
    'typeId' => '11',
    'type' => 2,
    'subject' => '杨某驾驶改装小型客车（核载9人，实载64人，其中62人为幼儿园学生），行至榆林子镇马槽沟村处，占用对向车道逆行时与一辆重型自卸货车正面碰撞，造成22人死亡、44人受伤.该起事故中的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '货车超速行驶',
    'optionB' => '非法改装机动车',
    'optionC' => '客车超员',
    'optionD' => '客车逆向行驶',
    'answer' => '2,3,4',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、改装小型客车，所以非法改装机动车；2、核载9人，实载64人，所以客车超员；3、占用对向车道逆行时，所以客车逆向行驶。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  3 => 
  array (
    'id' => 5503,
    'typeId' => '11',
    'type' => 2,
    'subject' => '邹某驾驶大型卧铺客车（核载35人，实载47人），行至京港澳高速公路938公里时，因乘车人携带的大量危险化学品在车厢内突然发生爆燃，造成41人死亡，6人受伤.此事故中的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '客车超员',
    'optionB' => '乘车人携带易燃易爆危险物品',
    'optionC' => '超速行驶',
    'optionD' => '不按规定停车',
    'answer' => '1,2',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、核载35人，实载47人为超载；2、乘车人携带的大量危险化学品。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  4 => 
  array (
    'id' => 5505,
    'typeId' => '11',
    'type' => 2,
    'subject' => '某日3时40分，孙某驾驶大客车（乘载54人、核载55人）行至随岳高速公路229公里加300米处，在停车下客过程中，被后方驶来李某驾驶的重型半挂机动车追尾，造成26人死亡，29人受伤.事后查明，李某从昨日18时许出发，途中一直未休息.双方驾驶人的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '孙某违法停车',
    'optionB' => '孙某客车超员',
    'optionC' => '李某超速',
    'optionD' => '李某疲劳驾驶',
    'answer' => '1,4',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、高速公路上不允许停车下客。2、李某从昨日18时许出发，途中一直未休息。故属于疲劳驾驶。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  5 => 
  array (
    'id' => 5506,
    'typeId' => '11',
    'type' => 2,
    'subject' => '钱某驾驶大型卧铺客车，乘载45人（核载40人），保持40公里/小时以上的车速行至八宿县境内连续下坡急转弯路段处，翻下100米深的山崖，造成17人死亡、20人受伤.钱某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '驾驶时接听手持电话',
    'optionB' => '超速行驶',
    'optionC' => '客车超员',
    'optionD' => '疲劳驾驶',
    'answer' => '2,3',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、弯道限速30公里/每小时，故超速行驶。2、乘载45人(核载40人)，故客车超员。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  6 => 
  array (
    'id' => 5507,
    'typeId' => '11',
    'type' => 2,
    'subject' => '吴某驾驶一辆大客车，乘载33人（核载22人），行至163县道7公里加300米处时，机动车失控坠入山沟，造成10人死亡、21人受伤.事后经酒精检测，吴某血液酒精含量为26毫克/百毫升.吴某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '超速行驶',
    'optionB' => '客车超员',
    'optionC' => '疲劳驾驶',
    'optionD' => '酒后驾驶',
    'answer' => '2,4',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、乘载33人(核载22人)，所以客车超员；2、吴某血液酒精含量为26毫克/百毫升，所以酒后驾驶。（此处既然检测到酒精就算酒后驾驶，不然人的血液里边哪里会有酒精）',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  7 => 
  array (
    'id' => 5508,
    'typeId' => '11',
    'type' => 2,
    'subject' => '李某驾驶一辆大客车，乘载21人（核载35人），行驶途中察觉制动装置有异常但未处理，行至某海湾大桥时时速为50公里（该路段限速40公里），因制动失灵坠入海中，造成13人死亡、8人受伤.李某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '超速行驶',
    'optionB' => '疲劳驾驶',
    'optionC' => '客车超员',
    'optionD' => '驾驶具有安全隐患的机动车',
    'answer' => '1,4',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、察觉制动装置有异常但未处理，所以为驾驶故障机动车。2、行至双岛海湾大桥时时速为50公里(该路段限速40公里)所以为超速行驶。此题注意核载35人就是规定可以做35个人，实际乘坐21人所以没有客车超员。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  8 => 
  array (
    'id' => 5509,
    'typeId' => '11',
    'type' => 2,
    'subject' => '唐某驾驶一辆大客车，乘载74人（核载30人），以每小时38公里的速度，行至一连续下陡坡转弯路段时，机动车翻入路侧溪水内，造成17人死亡、57人受伤.唐某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '酒后驾驶',
    'optionB' => '客车超员',
    'optionC' => '疲劳驾驶',
    'optionD' => '超速行驶',
    'answer' => '2,4',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、乘载74人(核载30人)所以客车超员。2、弯道限速30公里/每小时，所以超速行驶。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  9 => 
  array (
    'id' => 5510,
    'typeId' => '11',
    'type' => 2,
    'subject' => '某日19时，杨某驾驶大客车，乘载57人（核载55人），连续行驶至次日凌晨1时，在金城江区境内050国道3008公里加110米处，因机动车左前胎爆裂，造成12人死亡、22人受伤的特大交通事故.杨某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '疲劳驾驶',
    'optionB' => '客车超员',
    'optionC' => '超速行驶',
    'optionD' => '操作不当',
    'answer' => '1,2',
    'optionSimple' => NULL,
    'solve' => '违法行为：1、题目提到连续行驶到次日凌晨1时，属疲劳驾驶。2、题目提到只能做55以上，却坐了57人，属客车超员。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  10 => 
  array (
    'id' => 5511,
    'typeId' => '11',
    'type' => 2,
    'subject' => '叶某驾驶中型厢式货车，行至某弯道路段时，以40公里/小时的速度与王某驾驶的乘载19人正三轮载货摩托车发生正面相撞，造成10人死亡、9人受伤.双方驾驶人的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '叶某驾驶与准驾车型不符的机动车',
    'optionB' => '王某驾驶摩托车非法载客',
    'optionC' => '叶某超速行驶',
    'optionD' => '王某不按信号灯指示行驶',
    'answer' => '2,3',
    'optionSimple' => NULL,
    'solve' => '注意看题目，不是道路而是弯道，弯道的限速每小时/30以上，就算超速了。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  11 => 
  array (
    'id' => 5512,
    'typeId' => '11',
    'type' => 1,
    'subject' => '赵某（持有A2驾驶证）驾驶大型卧铺客车，行驶至叶城县境内219国道226公里加215米处转弯路段时，坠入道路一侧山沟，致16人死亡，26人受伤.赵某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '客车超员',
    'optionB' => '驾驶逾期未检验的机动车',
    'optionC' => '驾驶与准驾车型不符的机动车',
    'optionD' => '疲劳驾驶',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '持有A2驾驶证驾驶大型卧铺客车是违法的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  12 => 
  array (
    'id' => 5513,
    'typeId' => '11',
    'type' => 1,
    'subject' => '周某驾驶一辆轻型厢式货车（搭载22人）行驶至丙察公路79公里加150米处时，坠入道路一侧山崖，造成12人死亡、10人受伤.周某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '驾驶逾期未检验的机动车',
    'optionB' => '货运机动车载客',
    'optionC' => '超速行驶',
    'optionD' => '疲劳驾驶',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '货车上装人，属于严重违法。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  13 => 
  array (
    'id' => 5514,
    'typeId' => '11',
    'type' => 1,
    'subject' => '郝某驾驶一辆载有84.84吨货物的重型自卸货车（核载15.58吨），行至滦县境内262省道34公里加623米处，与前方同向行驶的一辆载有45.85吨货物的货车（核载1.71吨）追尾碰撞后，侧翻撞向路边人群，造成19人死亡、17人受伤.双方驾驶人共同的违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '超速行驶',
    'optionB' => '货车超载',
    'optionC' => '疲劳驾驶',
    'optionD' => '酒后驾驶',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '题目是在问共同的违法行为，明显是超载！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  14 => 
  array (
    'id' => 5515,
    'typeId' => '11',
    'type' => 1,
    'subject' => '佟某驾驶一辆大客车（乘载54人，核载55人）以45公里的时速行经泥泞路段时机动车侧滑段时，驶出路外坠入深沟，导致14人死亡、40人受伤.佟某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '客车超员',
    'optionB' => '超速行驶',
    'optionC' => '酒后驾驶',
    'optionD' => '疲劳驾驶',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路交通安全法实施条例》第四十六条：机动车行驶中遇有下列情形之一的，最高行驶速度不得超过每小时30公里，其中拖拉机、电瓶车、轮式专用机械车不得超过每小时15公里：(一)进出非机动车道，通过铁路道口、急弯路、窄路、窄桥时；(二)掉头、转弯、下陡坡时；(三)遇雾、雨、雪、沙尘、冰雹，能见度在50米以内时；(四)在冰雪、泥泞的道路上行驶时；(五)牵引发生故障的机动车时。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  15 => 
  array (
    'id' => 5516,
    'typeId' => '11',
    'type' => 1,
    'subject' => '徐某驾驶一辆中型客车（乘载27人）行至上坡路段车辆发生后，溜驶出路外坠入落差约80米的山崖，造成11人死亡、7人受伤.徐某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '疲劳驾驶',
    'optionB' => '酒后驾驶',
    'optionC' => '客车超员',
    'optionD' => '超速行驶',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '本题是超载。按照机动车核定的载客人数：大型客车是指核定载客人数20人以上（含20人）的载客汽车；中型客车是指核定载客人数10—19人（含19人）的载客汽车；小型客车是指核定载客人数小9人（含9人）的载客汽车；微型载客汽车是指核定载客人数8人以下（含8人）且排气量小于1升（含1升）的载客汽车。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  16 => 
  array (
    'id' => 5517,
    'typeId' => '11',
    'type' => 1,
    'subject' => '罗某驾驶大型卧铺客车（乘载44人，核载44人）行至沿河县境内540县道58公里加500米处时，在结冰路面以每小时44公里速度行驶，导致机动车侧滑翻下公路，造成15人死亡、27人受伤.罗某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '客车超员',
    'optionB' => '超速行驶',
    'optionC' => '疲劳驾驶',
    'optionD' => '操作不当',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路交通安全法实施条例》第四十六条：机动车行驶中遇有下列情形之一的，最高行驶速度不得超过每小时30公里，其中拖拉机、电瓶车、轮式专用机械车不得超过每小时15公里：(一)进出非机动车道，通过铁路道口、急弯路、窄路、窄桥时；(二)掉头、转弯、下陡坡时；(三)遇雾、雨、雪、沙尘、冰雹，能见度在50米以内时；(四)在冰雪、泥泞的道路上行驶时；(五)牵引发生故障的机动车时。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  17 => 
  array (
    'id' => 5518,
    'typeId' => '11',
    'type' => 1,
    'subject' => '何某驾驶一辆乘载53人的大客车（核载47人），在高速公路驾驶被一辆重型半挂牵引车追尾，导致大客车翻出路侧护栏并起火燃烧，造成17人死亡、27人受伤.何某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '超速行驶',
    'optionB' => '客车超员',
    'optionC' => '驾驶逾期未年检机动车',
    'optionD' => '操作不当',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '核载47人，实际乘载53人，超载；题干主要透漏的是这个违法信息！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  18 => 
  array (
    'id' => 5519,
    'typeId' => '11',
    'type' => 1,
    'subject' => '某日13时10分，罗某驾驶一辆中型客车从高速公路0公里处出发，下午14时10分行至该高速公路125公里加200米处时，发生追尾碰撞，机动车驶出路外造成11人死亡、2人受伤.罗某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '超速行驶',
    'optionB' => '不按交通标线行驶',
    'optionC' => '客车超员',
    'optionD' => '疲劳驾驶',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '因为，高速最高时速为120公里/小时，而案例中根据时间可推算出超速5.2公里，所以该案例为超速。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  19 => 
  array (
    'id' => 5520,
    'typeId' => '11',
    'type' => 1,
    'subject' => '某日早上6时，冉某驾驶一辆大客车出发，连续行驶至上午11时，在宣汉县境内宣南路1公里处，坠于公路一侧垂直高度8.5米的陡坎下，造成13人死亡、9人受伤.冉某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '超速行驶',
    'optionB' => '不按交通标线行驶',
    'optionC' => '客车超员',
    'optionD' => '疲劳驾驶',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '规定：连续4小时就要停车休息20分钟！本题连续驾驶5小时，属于疲劳驾驶。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  20 => 
  array (
    'id' => 5521,
    'typeId' => '11',
    'type' => 2,
    'subject' => '驾驶汽车超速行驶有哪些危害？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '反应距离延长',
    'optionB' => '视野变窄',
    'optionC' => '加重事故后果',
    'optionD' => '制动距离延长',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => 'A车速快，反应距离延长；B车速快2边的事物会比较模糊，视野就会窄；C车速快，由于惯性，碰撞引起的后果就严重；D车速快，制动距离自然延长。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  21 => 
  array (
    'id' => 5522,
    'typeId' => '11',
    'type' => 2,
    'subject' => '下列做法哪些可以有效避免驾驶疲劳？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '连续驾驶不超过4小时',
    'optionB' => '用餐不宜过饱',
    'optionC' => '保持良好的睡眠',
    'optionD' => '餐后适当休息后驾车',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '试题分析：可以有效避免驾驶疲劳有“连续驾驶不超过4小时”，“用餐不宜过饱”，“保持良好的睡眠”，“餐后适当休息后驾车”。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  22 => 
  array (
    'id' => 5523,
    'typeId' => '11',
    'type' => 2,
    'subject' => '行车中驾驶人接打手机或发短信有什么危害？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '影响乘车人休息',
    'optionB' => '分散驾驶注意力',
    'optionC' => '影响正常驾驶操作',
    'optionD' => '遇紧急情况反应不及',
    'answer' => '2,3,4',
    'optionSimple' => NULL,
    'solve' => '行车中危害有：1、会分散驾驶注意力；2、影响正常驾驶操作；3、遇紧急情况反应不及时。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  23 => 
  array (
    'id' => 5524,
    'typeId' => '11',
    'type' => 2,
    'subject' => '这个小型客车驾车人有哪些违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => 'https://www.jiazhao.com/images/tiku/201511231112205989.jpg',
    'optionA' => '接打手持电话',
    'optionB' => '无证驾驶',
    'optionC' => '酒后驾驶',
    'optionD' => '未系安全带',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '从通话中得知“刚喝完酒”和“没驾驶本”，从图片中可知“没系安全带”和“打电话”，均属于违法行为。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  24 => 
  array (
    'id' => 5525,
    'typeId' => '11',
    'type' => 0,
    'subject' => '变更车道前确认后方无来车时可以不开转向灯变道。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '变更车道时要提前开启转向灯，养成良好的开车习惯，防患于未然，因此本题错误。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  25 => 
  array (
    'id' => 5526,
    'typeId' => '11',
    'type' => 2,
    'subject' => '周某夜间驾驶大货车在没有路灯的城市道路上以90公里每小时的速度行驶,一直开启远光灯,在通过一窄路时,因加速抢道,导致对面驶来的一辆小客车撞上右侧护栏.周某的主要违法行为是什么?',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '超速行驶',
    'optionB' => '不按规定会车',
    'optionC' => '疲劳驾驶',
    'optionD' => '不按规定使用灯光',
    'answer' => '1,2,4',
    'optionSimple' => NULL,
    'solve' => '第一，夜间没有路灯的情况下90公里/小时，超速。第二，通过窄路时，应该会车减速行驶。第三，应该交替使用近远光灯。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  26 => 
  array (
    'id' => 5528,
    'typeId' => '11',
    'type' => 1,
    'subject' => '动画8中有几种违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '一种违法行为',
    'optionB' => '二种违法行为',
    'optionC' => '三种违法行为',
    'optionD' => '四种违法行为',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '有2种违法行为：1、遮挡号牌；2、占用非机动车道右转弯！这一题要特别注意“鸣喇叭催促前方机动车”不算违法行为。部分同学认为是三种违法行为，但实际考过学生反馈正确答案是有二种违法行为。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  27 => 
  array (
    'id' => 5529,
    'typeId' => '11',
    'type' => 1,
    'subject' => '动画7中有几种违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '一种违法行为',
    'optionB' => '二种违法行为',
    'optionC' => '三种违法行为',
    'optionD' => '四种违法行为',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '有2种违法行为：1、遮挡号牌；2、违反禁止左转弯标志！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  28 => 
  array (
    'id' => 5530,
    'typeId' => '11',
    'type' => 1,
    'subject' => '动画6中有几种违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '一种违法行为',
    'optionB' => '二种违法行为',
    'optionC' => '三种违法行为',
    'optionD' => '四种违法行为',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '有3种违法行为：1、打电话；2、不系安全带；3、与前方拥堵走应急车道！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  29 => 
  array (
    'id' => 5531,
    'typeId' => '11',
    'type' => 1,
    'subject' => '动画5中有几种违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '一种违法行为',
    'optionB' => '二种违法行为',
    'optionC' => '三种违法行为',
    'optionD' => '四种违法行为',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '有3种违法行为：1、开车打电话；2、酒后驾驶；3、无证驾驶。通过驾驶人打电话时的内容来体现是酒后驾驶，无证驾驶，驾驶人电话内容为:“刚喝完酒，在去驾校的路上，准备报名学个驾驶本”！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  30 => 
  array (
    'id' => 5532,
    'typeId' => '11',
    'type' => 1,
    'subject' => '动画4中有几种违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '一种违法行为',
    'optionB' => '二种违法行为',
    'optionC' => '三种违法行为',
    'optionD' => '四种违法行为',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '有3种违法行为：1、遮挡号牌；2、闯红灯；3、不按导向箭头行驶！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  31 => 
  array (
    'id' => 5533,
    'typeId' => '11',
    'type' => 1,
    'subject' => '动画3中有几种违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '一种违法行为',
    'optionB' => '二种违法行为',
    'optionC' => '三种违法行为',
    'optionD' => '四种违法行为',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '有2种违法行为：1、行驶中遮挡号牌；2、超速行驶！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  32 => 
  array (
    'id' => 5534,
    'typeId' => '11',
    'type' => 1,
    'subject' => '动画2中有几种违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '一种违法行为',
    'optionB' => '二种违法行为',
    'optionC' => '三种违法行为',
    'optionD' => '四种违法行为',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '有2种违法行为：1、打电话；2、堵车时占用公交车道通行！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  33 => 
  array (
    'id' => 5535,
    'typeId' => '11',
    'type' => 1,
    'subject' => '动画1中有几种违法行为？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '一种违法行为',
    'optionB' => '二种违法行为',
    'optionC' => '三种违法行为',
    'optionD' => '四种违法行为',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '有2种违法行为：1、打电话；2、不系安全带！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  34 => 
  array (
    'id' => 6829,
    'typeId' => '11',
    'type' => 1,
    'subject' => '魏某（驾驶证被扣留）驾驶小型客车（逾期未检验）沿某国道行驶至某处时跨双黄实线掉头，与对向车道于某驾驶的重型自卸货车相撞，造成5人死亡、2人受伤.事故发生后魏某驾车逃离事故现场.造成本起事故的直接原因是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '魏某驾驶机动车时跨双黄实线掉头',
    'optionB' => '于某超速行驶',
    'optionC' => '魏某驾驶逾期未检验的机动车',
    'optionD' => '魏某在驾驶证被扣留期间驾驶机动车',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '注意看清题目，问的是直接原因，虽然魏某存在多种违法行为，但是造成事故的主要原因是魏某驾驶机动车时跨双黄实线掉头。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  35 => 
  array (
    'id' => 6830,
    'typeId' => '11',
    'type' => 2,
    'subject' => '黄某（驾驶证被扣留）驾驶小型客车（逾期未检验）沿某国道行驶至某处时跨双黄实线掉头，与对向车道于某驾驶的重型自卸货车相撞，造成5人死亡、2人受伤.事故发生后黄某驾车逃离事故现场.本起事故中存在的违法行为有什么？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '黄某驾驶逾期未检验的机动车',
    'optionB' => '黄某在驾驶证被扣留期间驾驶机动车',
    'optionC' => '黄某驾驶机动车时跨双黄实线掉头',
    'optionD' => '于某超速行驶',
    'answer' => '1,2,3',
    'optionSimple' => NULL,
    'solve' => '黄某驾驶证被扣留期间驾驶机动车上道路行驶，属于无证驾驶，是违法行为；逾期未年检车辆上道路行驶违反《道路交通安全法》，是违法行为；压双黄实线掉头，属于违反标志标线指示通行，是违法行为。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  36 => 
  array (
    'id' => 6831,
    'typeId' => '11',
    'type' => 0,
    'subject' => '陈某驾驶小型普通客车行驶至某县道转弯路段时，在结冰湿滑路面上以63km/h的速度超越前方袁某驾驶的小型面包车（行驶速度28km/h）时两车刮擦后坠翻，造成6人死亡、1人受伤.本起事故驾驶人的违法行为是陈某超速行驶和违法超车。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路交通安全法实施条例》第四十六条 机动车行驶中遇有下列情形之一的，最高行驶速度不得超过每小时30公里，其中拖拉机、电瓶车、轮式专用机械车不得超过每小时15公里： （二）掉头、转弯、下陡坡时。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  37 => 
  array (
    'id' => 6832,
    'typeId' => '11',
    'type' => 0,
    'subject' => '驾驶人冯某驾驶大型普通客车在某高速公路隧道口（限速60km/h）以83km/h的速度冲撞隧道墙，造成36人死亡、13人受伤.调查表明冯某自前一日12时许至事故发生时没有休息.本次事故发生的直接原因是冯某超速行驶、疲劳驾驶。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '隧道口已标明限速60km/h，冯某仍以83km/h的速度行驶，属于超速行驶；连续驾驶机动车超过4小时未停车休息或者停车休息时间少于20分钟，属于疲劳驾驶，冯某自前一日12时起未休息，已构成上述行为。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  38 => 
  array (
    'id' => 6833,
    'typeId' => '11',
    'type' => 1,
    'subject' => '某日刘某与朋友相约打麻将，一直到次日凌晨4时，然后驾驶小型汽车回家，刚开一会儿就感觉头脑发沉，但因离家也就十分钟的路程了，刘某坚持继续驾驶.当车辆行驶至接近某路口时，刘某的车与前方一辆正常行驶的出租车相撞，造成两车损坏.此事故中的违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '出租车未按交通信号灯行驶',
    'optionB' => '刘某超载驾驶',
    'optionC' => '刘某疲劳驾驶',
    'optionD' => '出租车未及时避让',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '此事故中刘某明显存在疲劳驾驶行为。车辆无安全技术问题和道路、环境良好，并且出租车在正常行驶的情况下发生了事故，很明显事故的主要原因是刘某疲劳驾驶。 ',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  39 => 
  array (
    'id' => 6834,
    'typeId' => '11',
    'type' => 1,
    'subject' => '某日夜间下雨，陈某驾驶小型汽车与李某（未系安全带）一同回家，当陈某以120公里/小时车速行驶至城市主干路（限速80公里/小时）的某一路段时，车辆突然发生侧滑，导致与道路左侧护栏相撞后翻车.陈某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '操作不当',
    'optionB' => '未系安全带',
    'optionC' => '疲劳驾驶',
    'optionD' => '超速行驶',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '雨天以120公里/小时的速度行驶，超出80公里/小时的限速规定，所以是陈某超速行驶。雨天视线不好，应该降低车速。另未系安全带的应该是李某，而非陈某。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  40 => 
  array (
    'id' => 6835,
    'typeId' => '11',
    'type' => 2,
    'subject' => '贾某在能见度小于50米的雾天驾车在高速公路上以时速40公里行驶，贾某开启了雾灯、示廓灯、危险报警闪光灯，并与同车道前车保持50米距离，经过三个出口驶离高速公路.贾某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '未按规定开启相应的灯光',
    'optionB' => '未及时从最近的出口驶离高速公路',
    'optionC' => '与同车道前车距离不足',
    'optionD' => '超速行驶',
    'answer' => '1,2,4',
    'optionSimple' => NULL,
    'solve' => '能见度小于50米时，开启雾灯、近光灯、示廓灯、前后位灯和危险报警闪光灯，车速不得超过每小时20公里，并从最近的出口尽快驶离高速公路。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  41 => 
  array (
    'id' => 6837,
    'typeId' => '11',
    'type' => 2,
    'subject' => '赵某（持有A2驾驶证）驾驶大型卧铺客车（核载36人），行驶至叶城县境内某处急弯路段，加速超越前车时，坠入道路一侧山沟，致16人死亡，20人受伤.赵某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '疲劳驾驶',
    'optionB' => '驾驶逾期未检验的机动车',
    'optionC' => '驾驶与准驾车型不符的机动车',
    'optionD' => '在不具备超车条件的急弯路段加速超车',
    'answer' => '3,4',
    'optionSimple' => NULL,
    'solve' => '赵某的主要违法行为是在不具备超车条件的急弯路段加速超车和驾驶与准驾车型不符的机动车。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  42 => 
  array (
    'id' => 6838,
    'typeId' => '11',
    'type' => 2,
    'subject' => '驾驶汽车超速行驶有哪些危害？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '加重事故后果',
    'optionB' => '视野变窄',
    'optionC' => '制动距离延长',
    'optionD' => '反应距离延长',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '驾驶汽车超速行驶使得反应距离延长；同时过快的车速使得两边的事物会比较模糊，视野变窄；太快的车速，由于惯性作用，就会加重事故后果以及制动距离延长等危害。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  43 => 
  array (
    'id' => 7587,
    'typeId' => '11',
    'type' => 0,
    'subject' => '当你驾车在小区行驶时一定要注意儿童安全因为儿童安全意识较差且身材矮小不容易被发现。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  44 => 
  array (
    'id' => 8295,
    'typeId' => '11',
    'type' => 2,
    'subject' => '某日15时30分，张某驾驶一辆载货汽车（搭载10人）行至阳信县境内永莘路以47公里/小时的时速通过急弯路段时，机动车侧滑翻在道路以侧山沟，导致3人死亡，7人受伤。张某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '疲劳驾驶',
    'optionB' => '超速行驶',
    'optionC' => '客车超员',
    'optionD' => '载货车载客',
    'answer' => '2,4',
    'optionSimple' => NULL,
    'solve' => NULL,
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  45 => 
  array (
    'id' => 8296,
    'typeId' => '11',
    'type' => 2,
    'subject' => '王某无证驾驶两轮摩托车在同向1条车道的城市道路上以60公里/时的速度行驶,遇前方交通拥堵,在借道超车过程中与同向行驶的吴某驾驶的小型客车发生侧面碰撞.这起事故中的主要违法行为有哪些?',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '王某超速驾驶',
    'optionB' => '王某无证驾驶',
    'optionC' => '王某违法超车',
    'optionD' => '吴某不按规定让行',
    'answer' => '1,2,3',
    'optionSimple' => NULL,
    'solve' => '王某无证驾驶两轮摩托车在同向1条车道的城市道路上以60公里时的速度行驶遇前方交通拥堵在借道超车过程中与同向行驶的吴某驾驶的小型客车发生侧面碰撞这起事故中的主要违法行为有哪些',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  46 => 
  array (
    'id' => 8366,
    'typeId' => '11',
    'type' => 1,
    'subject' => '罗某驾驶大型客车实载44人核载44人，行至某县道在结冰路面以每小时44公里速度行驶，导致机动车侧滑翻下公路，造成15人死亡27人受伤。罗某的主要违法行为是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '操作不当',
    'optionB' => '客车超员',
    'optionC' => '超速行驶',
    'optionD' => '疲劳驾驶',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '按照规定，冰雪路面最高速度不能超过30公里/小时，题中在结冰路面以每小时44公里速度行驶，是超速行驶。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  47 => 
  array (
    'id' => 8402,
    'typeId' => '11',
    'type' => 0,
    'subject' => '某日早上6时冉某驾驶一辆大客车出发，连续行驶至上午11时，坠入公路一侧垂直高度85米的陡坎下，造成13人死亡9人受伤，冉某的主要违法行为是疲劳驾驶。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '根据规定：连续开车4小时要停车休息20分钟。本题中冉某已连续开车5个小时了，属于疲劳驾驶。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
);