<?php return array (
  0 => 
  array (
    'id' => 3303,
    'typeId' => '15',
    'type' => 2,
    'subject' => '机动车驾驶员培训依据（ ）实行分类许可。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '经营项目',
    'optionB' => '培训能力',
    'optionC' => '培训内容',
    'optionD' => '教练员数量',
    'answer' => '1,2,3',
    'optionSimple' => NULL,
    'solve' => '本题详情查看《机动车驾驶培训教练员》：机动车驾驶员培训依据经营项目、培训能力和培训内容实行分类许可。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  1 => 
  array (
    'id' => 3306,
    'typeId' => '15',
    'type' => 0,
    'subject' => '县级以上道路运输管理机构具体负责实施本行政区域内经营性道路运输从业人员的管理工作。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '本题详情查看《机动车驾驶培训教练员》：县级以上道路运输管理机构负责实施本行政区域内经营性道路运输从业人员的管理工作，以及教练员在教学过程中有道路交通安全违法行为或造成交通事故进行判决',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  2 => 
  array (
    'id' => 3329,
    'typeId' => '15',
    'type' => 0,
    'subject' => '大件运输车辆及装载物品的有关情况可以与《超限运输车辆通行证》记载的内容不一致。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《超限运输车辆行驶公路管理规定》第四十七条  大件运输车辆有下列情形之一的，视为违法超限运输:（一）未经许可擅自行驶公路的；（二）车辆及装载物品的有关情况与《超限运输车辆通行证》记载的内容不一致的；（三）未按许可的时间、路线、速度行驶公路的；（四）未按许可的护送方案采取护送措施的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  3 => 
  array (
    'id' => 3330,
    'typeId' => '15',
    'type' => 0,
    'subject' => '道路货物运输驾驶员进行超限运输时未随车携带《超限运输车辆通行证》，将被公路管理机构扣留车辆。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '未按照指定时间、路线和速度行驶的超限运输车辆且拒不改正的或者未随车携带超限运输车辆通行证，由公路管理机构或者公安机关交通管理部门责令改正；拒不改正的，公路管理机构或者公安机关交通管理部门可以扣留车辆。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  4 => 
  array (
    'id' => 3331,
    'typeId' => '15',
    'type' => 0,
    'subject' => '道路货物运输驾驶员使用伪造、变造的《超限运输车辆通行证》，由公路管理机构没收伪造、变造的超限运输车辆通行证，并处以罚款。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《公路安全保护条例》第六十五条第三款：租借、转让超限运输车辆通行证的，由公路管理机构没收超限运输车辆通行证，处1000元以上5000元以下的罚款。使用伪造、变造的超限运输车辆通行证的，由公路管理机构没收伪造、变造的超限运输车辆通行证，处3万元以下的罚款。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  5 => 
  array (
    'id' => 3332,
    'typeId' => '15',
    'type' => 0,
    'subject' => '道路货物运输车辆的技术等级应该达到二级以上。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '从事道路运输经营的车辆应当车辆技术等级应当达到二级以上。技术等级评定方法应当符合国家有关道路运输车辆技术等级划分和评定的要求。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  6 => 
  array (
    'id' => 3333,
    'typeId' => '15',
    'type' => 0,
    'subject' => '道路货物运输经营者可以对自有车辆进行二级维护作业，保证投入运营的车辆符合技术管理要求，并且必须进行二级维护竣工质量检测。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '道路运输经营者可以对自有车辆进行二级维护作业，保证投入运营的车辆符合技术管理要求，无需进行二级维护竣工质量检测',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  7 => 
  array (
    'id' => 3334,
    'typeId' => '15',
    'type' => 0,
    'subject' => '道路货物运输驾驶员不得擅自改变已获得道路运输证车辆的结构和特征。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路交通安全法》第十六条  任何单位或者个人不得有下列行为：1、拼装机动车或者擅自改变机动车已登记的结构、构造或者特征；2、改变机动车型号、发动机号、车架号或者车辆识别代号；3、伪造、变造或者使用伪造、变造的机动车登记证书、号牌、行驶证、检验合格标志、保险标志4、使用其他机动车的登记证书、号牌、行驶证、检验合格标志、保险标志。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  8 => 
  array (
    'id' => 3335,
    'typeId' => '15',
    'type' => 0,
    'subject' => '根据《道路运输从业人员管理规定》，申请人在从业资格考试中有舞弊行为的，取消当次考试资格，考试成绩无效。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '根据《道路运输从业人员管理规定》第二十三条申请人在从业资格考试中有舞弊行为的，取消当次考试资格，考试成绩无效。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  9 => 
  array (
    'id' => 3336,
    'typeId' => '15',
    'type' => 0,
    'subject' => '道路货物运输驾驶员违反从业资格管理规定且尚未接受处罚，可以直接办理从业资格证的换发、补发及变更手续。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第三十一条：交通运输主管部门和道路运输管理机构应当对符合要求的从业资格证件换发、补发、变更申请予以办理。申请人违反相关从业资格管理规定且尚未接受处罚的，受理机关应当在其接受处罚后换发、补发、变更相应的从业资格证件。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  10 => 
  array (
    'id' => 3337,
    'typeId' => '15',
    'type' => 0,
    'subject' => '道路货物运输驾驶员从业资格证违章记录栏内的记录是诚信考核和计分考核的依据。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第三十六条：交通主管部门和道路运输管理机构应当将道路运输从业人员的违章行为记录在《中华人民共和国道路运输从业人员从业资格证》的违章记录栏内，并通报发证机关。发证机关应当将该记录作为道路运输从业人员诚信考核和计分考核的依据，并存入管理档案。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  11 => 
  array (
    'id' => 3338,
    'typeId' => '15',
    'type' => 0,
    'subject' => '道路货物运输驾驶员在诚信考核周期内累计计分达到20分，且未按照规定参加继续教育培训，将被列入黑名单，并向社会公告。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '根据《道路运输驾驶员诚信考核办法》第二十七条　道路运输驾驶员有下列情形之一的，道路运输管理机构应当将其列入黑名单，并向社会公告：（一）在考核周期内累计计分达到20分，且未按照规定参加继续教育培训的；（二）无正当理由超过规定时间，未签注诚信考核等级的；（三）从业资格证件被吊销的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  12 => 
  array (
    'id' => 3341,
    'typeId' => '15',
    'type' => 0,
    'subject' => '春运、黄金周等客流高峰时，可以驾驶货车从事经营性道路旅客运输活动。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '春运、黄金周等客流高峰时，货运驾驶员不得驾驶货车从事经营性道路旅客运输活动。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  13 => 
  array (
    'id' => 3342,
    'typeId' => '15',
    'type' => 0,
    'subject' => '未取得道路危险货物运输许可，不得从事道路危险货物运输。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路危险货物运输管理规定》（2013年交通部令第2号）第五十九条：违反本规定，有下列情形之一的，由县级以上道路运输管理机构责令停止运输经营，有违法所得的，没收违法所得，处违法所得2倍以上10倍以下的罚款；没有违法所得或者违法所得不足2万元的，处3万元以上10万元以下的罚款；构成犯罪的，依法追究刑事责任：（一）未取得道路危险货物运输许可，擅自从事道路危险货物运输的；（二）使用失效、伪造、变造、被注销等无效道路危险货物运输许可证件从事道路危险货物运输的；（三）超越许可事项，从事道路危险货物运输的；（四）非经营性道路危险货物运输单位从事道路危险货物运输经营的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  14 => 
  array (
    'id' => 3343,
    'typeId' => '15',
    'type' => 0,
    'subject' => '驾驶员必须取得道路危险货物运输从业资格证，才能从事道路危险货物运输活动。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '驾驶员必须取得道路危险货物运输从业资格证，才能从事道路危险货物运输活动。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  15 => 
  array (
    'id' => 3344,
    'typeId' => '15',
    'type' => 0,
    'subject' => '可以将危险货物与普通货物混装运输。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路危险货物运输管理规定》第三十三条：不得使用罐式专用车辆或者运输有毒、感染性、腐蚀性危险货物的专用车辆运输普通货物。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  16 => 
  array (
    'id' => 3345,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员被道路运输企业聘用后，未参加安全生产教育和培训，将受到什么限制？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '只能进行短途运输',
    'optionB' => '运输时须他人陪同',
    'optionC' => '不得上岗作业',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '道路货物运输驾驶员被道路运输企业聘用后，未参加安全生产教育和培训，不得上岗作业。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  17 => 
  array (
    'id' => 3346,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员向监管部门举报所属企业不按规定进行车辆维护，这是行使了什么权利？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '获得工伤保护和民事赔偿',
    'optionB' => '对安全生产隐患进行批评、检举和控告',
    'optionC' => '拒绝违章指挥',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '根据《安全生产法》对于存在安全隐患的车辆，作为公司职员有权利和义务进行批评、检举和控告。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  18 => 
  array (
    'id' => 3347,
    'typeId' => '15',
    'type' => 0,
    'subject' => '劳动合同从何时起具有法律约束力？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '驾驶员入职上岗时',
    'optionB' => '劳动合同依法订立时',
    'optionC' => '驾驶员通过试用期时',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《劳动合同法》规定：建立劳动关系应当订立书面劳动合同。劳动合同依法订立即具有法律约束力。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  19 => 
  array (
    'id' => 3348,
    'typeId' => '15',
    'type' => 1,
    'subject' => '一般情况下，道路货物运输驾驶员解除劳动合同时应该如何通知道路运输企业？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '提前10日以书面形式通知',
    'optionB' => '提前30日以书面形式通知',
    'optionC' => '提前30日以口头形式通知',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《劳动合同法》第三十七条，劳动者提前三十日以书面形式通知用人单位，可以解除劳动合同。劳动者在试用期内提前三日通知用人单位，可以解除劳动合同。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  20 => 
  array (
    'id' => 3349,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员去某道路运输企业应聘，企业要求上交身份证，待入职之日归还，如何评价这种行为？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '双方协商决定是否上交身份证',
    'optionB' => '企业行为违反《劳动合同法》',
    'optionC' => '驾驶员必须将身份证上交给企业',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《劳动合同法》第九条：用人单位招用劳动者，不得扣押劳动者的居民身份证和其他证件，不得要求劳动者提供担保或者以其他名义向劳动者收取财物。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  21 => 
  array (
    'id' => 3350,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员去某道路运输企业应聘，企业要求收取500元的入职培训费，如何评价这种行为？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '双方协商决定是否缴纳培训费',
    'optionB' => '企业行为违反《劳动合同法》',
    'optionC' => '驾驶员必须缴纳这笔入职培训费',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '根据《劳动合同法》第二十二条　用人单位为劳动者提供专项培训费用，对其进行专业技术培训的，可以与该劳动者订立协议，约定服务期。劳动者违反服务期约定的，应当按照约定向用人单位支付违约金。违约金的数额不得超过用人单位提供的培训费用。用人单位要求劳动者支付的违约金不得超过服务期尚未履行部分所应分摊的培训费用。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  22 => 
  array (
    'id' => 3351,
    'typeId' => '15',
    'type' => 1,
    'subject' => '如何看待道路货物运输驾驶员拒绝企业管理人员违章指挥、强令冒险作业的行为？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '依法行使安全生产权利',
    'optionB' => '违反了企业管理规定',
    'optionC' => '违反了劳动合同',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '当企业管理人员提出违章指挥、强令冒险作业的行为，道路货物运输驾驶员应当拒绝，这是依法实行了安全生产权利。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  23 => 
  array (
    'id' => 3352,
    'typeId' => '15',
    'type' => 1,
    'subject' => '变更劳动合同时应该采用什么形式？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '电子',
    'optionB' => '口头',
    'optionC' => '书面',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《劳动合同法》第三十五条用人单位与劳动者协商一致，可以变更劳动合同约定的内容。变更劳动合同，应当采用书面形式。  变更后的劳动合同文本由用人单位和劳动者各执一份。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  24 => 
  array (
    'id' => 3353,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员应如何对待企业的《应急预案》和《应急演练组织办法》？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '阅读并熟知',
    'optionB' => '不予理会',
    'optionC' => '出事故后才需要了解',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '道路货物运输驾驶员应阅读并熟知企业的《应急预案》和《应急演练组织办法》',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  25 => 
  array (
    'id' => 3354,
    'typeId' => '15',
    'type' => 1,
    'subject' => '遇到法律、行政法规禁止运输的货物时，应该怎么做？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '直接运输',
    'optionB' => '少量运输',
    'optionC' => '拒绝运输',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《道路危险货物运输管理规定》第三十四条：道路危险货物运输企业或者单位不得运输法律、行政法规禁止运输的货物。  法律、行政法规规定的限运、凭证运输货物，道路危险货物运输企业或者单位应当按照有关规定办理相关运输手续。  法律、行政法规规定托运人必须办理有关手续后方可运输的危险货物，道路危险货物运输企业应当查验有关手续齐全有效后方可承运。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  26 => 
  array (
    'id' => 3355,
    'typeId' => '15',
    'type' => 1,
    'subject' => '遇到法律、行政法规规定必须办理有关手续后方可运输的货物时，应该怎么做？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '查验有关手续后运输',
    'optionB' => '按普通货物运输',
    'optionC' => '拒绝运输',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路危险货物运输管理规定》第三十四条：道路危险货物运输企业或者单位不得运输法律、行政法规禁止运输的货物。  法律、行政法规规定的限运、凭证运输货物，道路危险货物运输企业或者单位应当按照有关规定办理相关运输手续。  法律、行政法规规定托运人必须办理有关手续后方可运输的危险货物，道路危险货物运输企业应当查验有关手续齐全有效后方可承运。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  27 => 
  array (
    'id' => 3356,
    'typeId' => '15',
    'type' => 1,
    'subject' => '运输不可解体物品需要改装车辆时，应该由谁按照规定的车型和技术参数进行改装？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '具有资质的道路运输企业',
    'optionB' => '具有资质的车辆检验单位',
    'optionC' => '具有资质的车辆生产企业',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '运输不可解体物品需要改装车辆的，应当由具有相应资质的车辆生产企业按照规定的车型和技术参数进行改装，并依法向公安机关交通管理部门申请变更登记。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  28 => 
  array (
    'id' => 3357,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输经营者想承运一批外廓尺寸超过公路限宽、限长标准的不可解体货物，应该向哪个部门申请公路超限运输许可？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '公安交通管理部门',
    'optionB' => '城市管理部门',
    'optionC' => '交通运输管理部门',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《超限运输车辆行驶公路管理规定》第四条：交通运输部负责全国超限运输车辆行驶公路的管理工作。  县级以上地方人民政府交通运输主管部门负责本行政区域内超限运输车辆行驶公路的管理工作。  公路管理机构具体承担超限运输车辆行驶公路的监督管理。  县级以上人民政府相关主管部门按照职责分工，依法负责或者参与、配合超限运输车辆行驶公路的监督管理。交通运输主管部门应当在本级人民政府统一领导下，与相关主管部门建立治理超限运输联动工作机制。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  29 => 
  array (
    'id' => 3358,
    'typeId' => '15',
    'type' => 1,
    'subject' => '装载物易掉落、遗洒或者飘散时，图中哪种车辆更适合运输？',
    'subjectSimple' => NULL,
    'imgUrl' => 'http://qinhu-association-album.oss-cn-hangzhou.aliyuncs.com/admin/20210516211913/image-2075.jpg',
    'optionA' => 'A车',
    'optionB' => 'B车',
    'optionC' => 'C车',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '如图所示，本题应该选择更封闭的A车，适合装在易掉落、飘散的物品。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  30 => 
  array (
    'id' => 3359,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员一年内违法超限运输超过几次，将被责令停止从事营业性运输？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '1次',
    'optionB' => '2次',
    'optionC' => '3次',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《公路安全保护条例》第六十六条：对1年内违法超限运输超过3次的货运车辆，由道路运输管理机构吊销其车辆营运证；对1年内违法超限运输超过3次的货运车辆驾驶人，由道路运输管理机构责令其停止从事营业性运输；道路运输企业1年内违法超限运输的货运车辆超过本单位货运车辆总数10%的，由道路运输管理机构责令道路运输企业停业整顿；情节严重的，吊销其道路运输经营许可证，并向社会公告。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  31 => 
  array (
    'id' => 3360,
    'typeId' => '15',
    'type' => 1,
    'subject' => '根据《超限运输车辆行驶公路管理规定》，车货总高度从地面算起超过多少米的货车是超限运输车辆？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '5米',
    'optionB' => '4.3米',
    'optionC' => '4米',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '超限运输车辆，是指车货总高度从地面算起超过4米的运输车辆。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  32 => 
  array (
    'id' => 3361,
    'typeId' => '15',
    'type' => 1,
    'subject' => '根据《超限运输车辆行驶公路管理规定》，车货总宽度超过多少米的货车是超限运输车辆？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '2.25米',
    'optionB' => '2.55米',
    'optionC' => '3米',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《超限运输车辆行驶公路管理规定》第三条，本规定所称超限运输车辆，是指有下列情形之一的货物运输车辆：（二）车货总宽度超过2.55米。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  33 => 
  array (
    'id' => 3362,
    'typeId' => '15',
    'type' => 1,
    'subject' => '进行超限运输需要对道路进行加固、改造时，所需费用由谁承担？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '承运人',
    'optionB' => '托运人',
    'optionC' => '公路管理机构',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '根据《超限运输车辆行驶公路管理规定》公路管理机构具体承担超限运输车辆行驶公路的监督管理，需要采取加固、改造措施的，所需费用由承运人承担。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  34 => 
  array (
    'id' => 3363,
    'typeId' => '15',
    'type' => 1,
    'subject' => '大件运输车辆通行公路桥梁时，哪种做法是正确的？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '匀速居中行驶',
    'optionB' => '低速靠右行驶',
    'optionC' => '随意制动停车',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《超限运输车辆行驶公路管理规定》第二十条 经批准进行大件运输的车辆，行驶公路时应当遵守下列规定:（一）采取有效措施固定货物，按照有关要求在车辆上悬挂明显标志，保证运输安全；（二）按照指定的时间、路线和速度行驶；（三）车货总质量超限的车辆通行公路桥梁，应当匀速居中行驶，避免在桥上制动、变速或者停驶；（四）需要在公路上临时停车的，除遵守有关道路交通安全规定外，还应当在车辆周边设置警告标志，并采取相应的安全防范措施；需要较长时间停车或者遇有恶劣天气的，应当驶离公路，就近选择安全区域停靠；（五）通行采取加固、改造措施的公路设施，承运人应当提前通知该公路设施的养护管理单位，由其加强现场管理和指导；（六）',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  35 => 
  array (
    'id' => 3364,
    'typeId' => '15',
    'type' => 1,
    'subject' => '大件运输车辆需要较长时间停车时，哪种做法是正确的？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '在应急车道停车，设置警告标志',
    'optionB' => '驶离公路，在附近安全区域停车',
    'optionC' => '在避险车道停车，采取防范措施',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《超限运输车辆行驶公路管理规定》第二十条  经批准进行大件运输的车辆，行驶公路时应当遵守下列规定:（一）采取有效措施固定货物，按照有关要求在车辆上悬挂明显标志，保证运输安全；（二）按照指定的时间、路线和速度行驶；（三）车货总质量超限的车辆通行公路桥梁，应当匀速居中行驶，避免在桥上制动、变速或者停驶；（四）需要在公路上临时停车的，除遵守有关道路交通安全规定外，还应当在车辆周边设置警告标志，并采取相应的安全防范措施；需要较长时间停车或者遇有恶劣天气的，应当驶离公路，就近选择安全区域停靠；（五）通行采取加固、改造措施的公路设施，承运人应当提前通知该公路设施的养护管理单位，由其加强现场管理和指导；（六',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  36 => 
  array (
    'id' => 3365,
    'typeId' => '15',
    'type' => 1,
    'subject' => '申请公路超限运输许可时，隐瞒有关情况或者提供虚假材料，几年内不准申请公路超限运输许可？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '1年',
    'optionB' => '2年',
    'optionC' => '3年',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《超限运输车辆行驶公路管理规定》第四十八条：承运人隐瞒有关情况或者提供虚假材料申请公路超限运输许可的，除依法给予处理外，并在1年内不准申请公路超限运输许可。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  37 => 
  array (
    'id' => 3366,
    'typeId' => '15',
    'type' => 1,
    'subject' => '国际道路运输车辆的技术等级必须达到哪级？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '一级',
    'optionB' => '二级',
    'optionC' => '三级',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《国际道路运输管理规定》第五条，申请从事国际道路运输经营活动的，应当具备下列条件：  （一）已经取得国内道路运输经营许可证的企业法人；  （二）从事国内道路运输经营满3年，且近3年内未发生重大以上道路交通责任事故。  道路交通责任事故是指驾驶人员负同等或者以上责任的交通事故。  （三）驾驶人员符合第六条的条件。从事危险货物运输的驾驶员、装卸管理员、押运员，应当符合危险货物运输管理的有关规定；  （四）拟投入国际道路运输经营的运输车辆技术等级达到一级；  （五）有健全的安全生产管理制度。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  38 => 
  array (
    'id' => 3367,
    'typeId' => '15',
    'type' => 1,
    'subject' => '货车的外廓尺寸、轴荷和最大允许总质量应该符合哪个标准的要求？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '《汽车、挂车及汽车列车外廓尺寸、轴荷及质量限值》（GB 1589）',
    'optionB' => '《营运货车燃料消耗量限值及测量方法》（JT 719）',
    'optionC' => '《道路运输车辆综合性能要求和检验方法》（GB 18565）',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路运输车辆技术管理规定》第七条，从事道路运输经营的车辆应当符合下列技术要求：（一）车辆的外廓尺寸、轴荷和最大允许总质量应当符合《道路车辆外廓尺寸、轴荷及质量限值》（GB 1589）的要求。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  39 => 
  array (
    'id' => 3368,
    'typeId' => '15',
    'type' => 1,
    'subject' => '车辆所有权转移、转籍时，车辆技术档案应如何处理？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '随车移交',
    'optionB' => '随即失效',
    'optionC' => '保留两年',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路运输车辆技术管理规定》第十四条，道路运输经营者应当建立车辆技术档案制度，实行一车一档。档案内容应当主要包括：车辆基本信息，车辆技术等级评定、客车类型等级评定或者年度类型等级评定复核、车辆维护和修理（含《机动车维修竣工出厂合格证》）、车辆主要零部件更换、车辆变更、行驶里程、对车辆造成损伤的交通事故等记录。档案内容应当准确、详实。  车辆所有权转移、转籍时，车辆技术档案应当随车移交。  道路运输经营者应当运用信息化技术做好道路运输车辆技术档案管理工作。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  40 => 
  array (
    'id' => 3369,
    'typeId' => '15',
    'type' => 1,
    'subject' => '车辆日常维护由谁实施？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '维修企业',
    'optionB' => '运输企业',
    'optionC' => '驾驶员',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《道路运输车辆技术管理规定》第十五条，道路运输经营者应当建立车辆维护制度。车辆维护分为日常维护、一级维护和二级维护。日常维护由驾驶员实施，一级维护和二级维护由道路运输经营者组织实施，并做好记录。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  41 => 
  array (
    'id' => 3370,
    'typeId' => '15',
    'type' => 1,
    'subject' => '车辆一级维护由谁组织实施？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '运输企业',
    'optionB' => '驾驶员',
    'optionC' => '维修企业',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路运输车辆技术管理规定》第十五条：道路运输经营者应当建立车辆维护制度。车辆维护分为日常维护、一级维护和二级维护。日常维护由驾驶员实施，一级维护和二级维护由道路运输经营者组织实施，并做好记录。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  42 => 
  array (
    'id' => 3371,
    'typeId' => '15',
    'type' => 1,
    'subject' => '车辆二级维护由谁组织实施？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '管理部门',
    'optionB' => '运输企业',
    'optionC' => '维修企业',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '根据《道路运输车辆维护管理规定》车辆二级维护由运输企业组织实施。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  43 => 
  array (
    'id' => 3372,
    'typeId' => '15',
    'type' => 1,
    'subject' => '车辆维护周期由谁结合车辆类别、车辆运行状况、行驶里程、道路条件、使用年限等因素决定？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '相关法规',
    'optionB' => '运输企业',
    'optionC' => '管理部门',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路运输车辆技术管理规定》第十六条，道路运输经营者应当依据国家有关标准和车辆维修手册、使用说明书等，结合车辆类别、车辆运行状况、行驶里程、道路条件、使用年限等因素，自行确定车辆维护周期，确保车辆正常维护。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  44 => 
  array (
    'id' => 3373,
    'typeId' => '15',
    'type' => 1,
    'subject' => '普通货车自首次取得《道路运输证》当月起，每隔多长时间进行一次综合性能检测和技术等级评定？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '每6个月',
    'optionB' => '每12个月',
    'optionC' => '每18个月',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路运输车辆技术管理规定》第二十条，道路运输经营者应当自道路运输车辆首次取得《道路运输证》当月起，按照下列周期和频次，委托汽车综合性能检测机构进行综合性能检测和技术等级评定：  （一）客车、危货运输车自首次经国家机动车辆注册登记主管部门登记注册不满60个月的，每12个月进行1次检测和评定；超过60个月的，每6个月进行1次检测和评定。  （二）其它运输车辆自首次经国家机动车辆注册登记主管部门登记注册的，每12个月进行1次检测和评定。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  45 => 
  array (
    'id' => 3374,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路运输从业人员从业资格考试成绩多长时间内有效？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '1年',
    'optionB' => '2年',
    'optionC' => '3年',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第二十条：道路运输从业人员从业资格考试成绩有效期为1年，考试成绩逾期作废。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  46 => 
  array (
    'id' => 3375,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员从业资格证的有效期是几年？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '3年',
    'optionB' => '5年',
    'optionC' => '6年',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第二十九条：道路运输从业人员从业资格证件有效期为6年。道路运输从业人员应当在从业资格证件有效期届满30日前到原发证机关办理换证手续。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  47 => 
  array (
    'id' => 3376,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员应在从业资格证有效期届满多少日前办理换证手续？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '30日',
    'optionB' => '20日',
    'optionC' => '10日',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第二十九条：道路运输从业人员从业资格证件有效期为6年。道路运输从业人员应当在从业资格证件有效期届满30日前到原发证机关办理换证手续。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  48 => 
  array (
    'id' => 3377,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员遗失从业资格证后，应到原发证机关办理什么手续？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '换发',
    'optionB' => '补发',
    'optionC' => '变更',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第二十九条：道路运输从业人员从业资格证件有效期为6年。道路运输从业人员应当在从业资格证件有效期届满30日前到原发证机关办理换证手续。  道路运输从业人员从业资格证件遗失、毁损的，应当到原发证机关办理证件补发手续。  道路运输从业人员服务单位变更的，应当到交通运输主管部门或者道路运输管理机构办理从业资格证件变更手续。  道路运输从业人员从业资格档案应当由原发证机关在变更手续办结后30日内移交户籍迁入地或者现居住地的交通运输主管部门或者道路运输管理机构。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  49 => 
  array (
    'id' => 3378,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员的服务单位发生变化时，应到交通运输主管部门或者道路运输管理机构办理什么手续？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '证件补发',
    'optionB' => '证件换发',
    'optionC' => '证件变更',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第二十九条：道路运输从业人员从业资格证件有效期为6年。道路运输从业人员应当在从业资格证件有效期届满30日前到原发证机关办理换证手续。  道路运输从业人员从业资格证件遗失、毁损的，应当到原发证机关办理证件补发手续。  道路运输从业人员服务单位变更的，应当到交通运输主管部门或者道路运输管理机构办理从业资格证件变更手续。  道路运输从业人员从业资格档案应当由原发证机关在变更手续办结后30日内移交户籍迁入地或者现居住地的交通运输主管部门或者道路运输管理机构。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  50 => 
  array (
    'id' => 3379,
    'typeId' => '15',
    'type' => 1,
    'subject' => '从业资格证超过有效期180日未换证，发证机关将作何处理？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '吊销',
    'optionB' => '注销',
    'optionC' => '补发',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第三十二条，道路运输从业人员有下列情形之一的，由发证机关注销其从业资格证件：（五）超过从业资格证件有效期180日未申请换证的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  51 => 
  array (
    'id' => 3380,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员诚信考核和计分考核的周期是多长时间？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '6个月',
    'optionB' => '12个月',
    'optionC' => '24个月',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第三十四条：道路运输从业人员诚信考核和计分考核周期为12个月，从初次领取从业资格证件之日起计算。诚信考核等级分为优良、合格、基本合格和不合格，分别用AAA级、AA级、A级和B级表示。在考核周期内，累计计分超过规定的，诚信考核等级为B级。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  52 => 
  array (
    'id' => 3381,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员诚信考核的周期从何时开始计算？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '初次领取从业资格证',
    'optionB' => '初次签注诚信考核等级',
    'optionC' => '初次执行运输任务',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第三十四条：道路运输从业人员诚信考核和计分考核周期为12个月，从初次领取从业资格证件之日起计算。诚信考核等级分为优良、合格、基本合格和不合格，分别用AAA级、AA级、A级和B级表示。在考核周期内，累计计分超过规定的，诚信考核等级为B级。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  53 => 
  array (
    'id' => 3382,
    'typeId' => '15',
    'type' => 1,
    'subject' => '诚信考核等级为B级，且存在重大安全隐患的道路货物运输驾驶员会受到什么惩罚？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '批评、教育',
    'optionB' => '调离驾驶员工作岗位',
    'optionC' => '罚款',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '根据《道路运输驾驶员诚信考核办法》第二十四条：道路运输经营者应当加强对诚信考核等级为B级的道路运输驾驶员的教育和管理。对存在重大安全隐患的，应当及时调离驾驶员工作岗位。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  54 => 
  array (
    'id' => 3383,
    'typeId' => '15',
    'type' => 1,
    'subject' => '道路货物运输驾驶员应该如何使用从业资格证？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '运输时携带从业资格证',
    'optionB' => '使用没有年度诚信考核签注的从业资格证',
    'optionC' => '使用过期的从业资格证',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《道路运输从业人员管理规定》第三十六条，道路运输从业人员在从事道路运输活动时，应当携带相应的从业资格证件，并应当遵守国家相关法规和道路运输安全操作规程，不得违法经营、违章作业。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  55 => 
  array (
    'id' => 3384,
    'typeId' => '15',
    'type' => 1,
    'subject' => '大件运输车辆夜间停车休息时应设置什么装置？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '标志旗',
    'optionB' => '路障',
    'optionC' => '标志灯',
    'optionD' => '',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《道路货物运输知识》上注明：运输大型物件的车辆，夜晚行车和停车休息时应悬挂、设置标志灯。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  56 => 
  array (
    'id' => 3385,
    'typeId' => '15',
    'type' => 2,
    'subject' => '道路货物运输驾驶员如何保障运输安全？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '熟知相关规章制度和操作规程',
    'optionB' => '了解事故预防及应急处理措施',
    'optionC' => '掌握本岗位安全驾驶操作技能',
    'optionD' => '知悉自身的安全生产权利义务',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '道路货物运输驾驶员为了保障运输安全应当做到以下几点：熟知相关规章制度和操作规程、掌握本岗位安全驾驶操作技能、了解事故预防及应急处理措施、知悉自身的安全生产权利义务。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  57 => 
  array (
    'id' => 3386,
    'typeId' => '15',
    'type' => 2,
    'subject' => '道路货物运输驾驶员与道路运输企业订立劳动合同时，应该确认载明哪些事项？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '防止职业危害',
    'optionB' => '保障劳动安全',
    'optionC' => '免除事故责任',
    'optionD' => '办理工伤保险',
    'answer' => '1,2,4',
    'optionSimple' => NULL,
    'solve' => '《安全生产法》第四十九条：生产经营单位与从业人员订立的劳动合同，应当载明有关保障从业人员劳动安全、防止职业危害的事项，以及依法为从业人员办理工伤保险的事项。  生产经营单位不得以任何形式与从业人员订立协议，免除或者减轻其对从业人员因生产安全事故伤亡依法应承担的责任。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  58 => 
  array (
    'id' => 3441,
    'typeId' => '15',
    'type' => 0,
    'subject' => '停车一般应采用预见性制动。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '本题详情查看《机动车驾驶培训教练员》：停车一般应采用预见性制动。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  59 => 
  array (
    'id' => 3443,
    'typeId' => '15',
    'type' => 0,
    'subject' => '驾驶操作的准确性主要表现在动作的方向、幅度、速度和力量的把握四个方面。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '驾驶操作的准确性主要表现在动作的方向、幅度、速度和力量的把握四个方面。对的',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  60 => 
  array (
    'id' => 3492,
    'typeId' => '15',
    'type' => 1,
    'subject' => '机动车在高速公路上发生故障时，警告标志应当设置在故障车来车方向--以外。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '30米',
    'optionB' => '50米',
    'optionC' => '100米',
    'optionD' => '150米',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '交通安全规则可知，机动车在高速公路上发生故障时，警告标志应当设置在故障车来车方向一百五十米以外，车上人员应当迅速转移到右侧路肩上或者应急车道内，并且迅速报警。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  61 => 
  array (
    'id' => 8332,
    'typeId' => '15',
    'type' => 0,
    'subject' => '松懈情绪造成注意力不集中，不会使训练成绩停顿。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '松懈情绪造成注意力不集中，怎么可能不会使训练成绩停顿。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  62 => 
  array (
    'id' => 8333,
    'typeId' => '15',
    'type' => 2,
    'subject' => '运用胸外心脏按压法抢救伤员时，正确的做法是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '每分钟按压80至100次',
    'optionB' => '每15次按压后做2次口对口人工呼吸',
    'optionC' => '双臂伸直，双手交叉重叠，用手掌根垂直用力',
    'optionD' => '每次下压胸部4至5厘米后自然放松',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  63 => 
  array (
    'id' => 8334,
    'typeId' => '15',
    'type' => 2,
    'subject' => '发生交通事故后，防止继发事故的有效措施是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确放置危险警告标志',
    'optionB' => '正确疏散人员',
    'optionC' => '开启危险报警闪光灯',
    'optionD' => '标记伤员的原始位置',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  64 => 
  array (
    'id' => 8335,
    'typeId' => '15',
    'type' => 2,
    'subject' => '在高速公路上发生交通事故后，应及时疏散人员至___的安全的区域。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '高速公路行车道附近',
    'optionB' => '高速公路以外',
    'optionC' => '车后150米以外',
    'optionD' => '车前150米以外',
    'answer' => '2,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  65 => 
  array (
    'id' => 8336,
    'typeId' => '15',
    'type' => 2,
    'subject' => '道路交通事故现场的保护措施主要是？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '保护事故痕迹',
    'optionB' => '确定事故现场范围',
    'optionC' => '疏散人群，防止继发事故',
    'optionD' => '标注伤员位置',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  66 => 
  array (
    'id' => 8337,
    'typeId' => '15',
    'type' => 2,
    'subject' => '发生交通事故并造成人员受伤时，应___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '采取措施防止继发事故',
    'optionB' => '抢救伤员',
    'optionC' => '保护事故现场',
    'optionD' => '立即报警',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  67 => 
  array (
    'id' => 8338,
    'typeId' => '15',
    'type' => 2,
    'subject' => '在酸碱等腐蚀性化学品外泄的事故现场救助伤员时，正确的自我防护措施是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '远离泄漏的化学品',
    'optionB' => '带好防护手套',
    'optionC' => '远离受污染的伤员',
    'optionD' => '用湿毛巾外敷口鼻',
    'answer' => '2,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  68 => 
  array (
    'id' => 8339,
    'typeId' => '15',
    'type' => 2,
    'subject' => '对严重烧伤的伤员，正确的救护措施是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '对烧伤部位喷洒冷水',
    'optionB' => '用油膏涂抹烧伤的部位',
    'optionC' => '让伤员适量饮用淡盐水',
    'optionD' => '迅速灭火，并脱去燃烧的衣物',
    'answer' => '1,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  69 => 
  array (
    'id' => 8340,
    'typeId' => '15',
    'type' => 2,
    'subject' => '在交通事故现场对伤员进行救助时，实施救助的场所应该选择___的场地。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '道路外空阔',
    'optionB' => '夜间有照明',
    'optionC' => '救护汽车易接近',
    'optionD' => '交叉路口、弯道和坡道以外',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  70 => 
  array (
    'id' => 8341,
    'typeId' => '15',
    'type' => 2,
    'subject' => '无法避免与前车发生追尾时，驾驶员正确的应急驾驶姿势是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '握紧转向盘',
    'optionB' => '身体向后倾斜，紧靠座椅后背',
    'optionC' => '双脚勾紧脚踏板',
    'optionD' => '头部紧贴座椅头枕',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  71 => 
  array (
    'id' => 8342,
    'typeId' => '15',
    'type' => 2,
    'subject' => '无法避免与对向来车发生正面偏置碰撞（碰撞位置在驾驶员位置）且撞击力较大时，驾驶员正确的应急驾驶姿势是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '迅速将两腿抬起',
    'optionB' => '两腿蹬直',
    'optionC' => '往副驾驶座位躲避',
    'optionD' => '迅速躲离转向盘',
    'answer' => '1,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  72 => 
  array (
    'id' => 8343,
    'typeId' => '15',
    'type' => 2,
    'subject' => '无法避免与对向来车发生正面偏置碰撞（碰撞位置在副驾驶员位置）且撞击力较小时，驾驶员正确的应急驾驶姿势是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '握紧转向盘',
    'optionB' => '两腿弯曲',
    'optionC' => '身体向后倾斜，紧靠座椅后背',
    'optionD' => '两腿蹬直',
    'answer' => '1,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  73 => 
  array (
    'id' => 8344,
    'typeId' => '15',
    'type' => 2,
    'subject' => '无法避免与对向来车发生正面碰撞时，驾驶员___，尽量降低对自己和乘员的伤害程度。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '应保持正确的应急驾驶姿势',
    'optionB' => '应打开车门跳车',
    'optionC' => '可以改变行驶方向，使正面碰撞变为刮擦',
    'optionD' => '不能改变行驶方向',
    'answer' => '1,3',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  74 => 
  array (
    'id' => 8345,
    'typeId' => '15',
    'type' => 2,
    'subject' => '有效预防汽车发生制动失效的措施是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确使用制动，防止热衰退',
    'optionB' => '行车前检查制动踏板的自由行程',
    'optionC' => '定期维护制动系统',
    'optionD' => '行车前检查制动管路是否有滴漏',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  75 => 
  array (
    'id' => 8346,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车高速行驶中出现制动失效时，驾驶员可___，尽快安全地减速停车。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '拉紧驻车制动器',
    'optionB' => '抢挂低挡',
    'optionC' => '握稳转向盘',
    'optionD' => '利用天然屏障减速',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  76 => 
  array (
    'id' => 8347,
    'typeId' => '15',
    'type' => 2,
    'subject' => '行车中，易导致汽车制动失效的主要原因是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '轮胎胎面磨损严重',
    'optionB' => '制动器过热',
    'optionC' => '轮胎气压不合适',
    'optionD' => '制动系出现机械故障',
    'answer' => '2,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  77 => 
  array (
    'id' => 8348,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车使用过程中，有效预防发生转向失控的措施是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '定期维护转向系',
    'optionB' => '制动时防止前轮抱死',
    'optionC' => '行车前检查转向系是否松动',
    'optionD' => '行车前检查转向盘的间隙',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  78 => 
  array (
    'id' => 8349,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车高速行驶中出现转向失控时，驾驶员应___，尽快地减速停车。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '立即发出警示信号',
    'optionB' => '合理使用行车制动和驻车制动，避免紧急制动',
    'optionC' => '抢挂低挡',
    'optionD' => '紧急制动',
    'answer' => '1,2,3',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  79 => 
  array (
    'id' => 8350,
    'typeId' => '15',
    'type' => 2,
    'subject' => '行车中，易导致汽车转向失控的主要原因有___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '路面光滑且车速过快',
    'optionB' => '制动时前轮抱死',
    'optionC' => '轮胎气压不符合要求',
    'optionD' => '转向系出现机械故障',
    'answer' => '1,2,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  80 => 
  array (
    'id' => 8351,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车在使用过程中，有效预防发生爆胎的措施有___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '合理装载',
    'optionB' => '定期对轮胎进行换位',
    'optionC' => '检查轮胎气压是否满足要求',
    'optionD' => '检查轮胎的磨损情况',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  81 => 
  array (
    'id' => 8352,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车高速行驶中出现爆胎时，驾驶员应___，有效地减速停车。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '握稳转向盘，猛踩制动踏板',
    'optionB' => '抢挂低挡后，缓踩制动踏板',
    'optionC' => '在车速降低后，抢挂低挡',
    'optionD' => '在车速降低后，拉紧驻车制动器',
    'answer' => '2,3',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  82 => 
  array (
    'id' => 8353,
    'typeId' => '15',
    'type' => 2,
    'subject' => '行车中，易导致汽车爆胎的主要原因有___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '超载',
    'optionB' => '轮胎气压过低',
    'optionC' => '轮胎气压过高',
    'optionD' => '轮胎过度磨损',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  83 => 
  array (
    'id' => 8354,
    'typeId' => '15',
    'type' => 2,
    'subject' => '在紧急情况下，驾驶员应当___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '避重就轻，先人后物',
    'optionB' => '冷静判断，果断处置',
    'optionC' => '先制动减速，后控制方向',
    'optionD' => '先控制方向，后制动减速',
    'answer' => '1,2,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  84 => 
  array (
    'id' => 8355,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车通过窄桥前，教练员应提示学员___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '提前减速，靠中间慢行',
    'optionB' => '观察周边的交通情况',
    'optionC' => '避免在桥上会车、超车',
    'optionD' => '紧跟前车通过',
    'answer' => '1,2,3',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  85 => 
  array (
    'id' => 8356,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车准备通过漫水桥时，教练员应指导学员___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '握稳转向盘，快速通过',
    'optionB' => '握稳转向盘，低速通过',
    'optionC' => '按照预先选择好的行车路线通过',
    'optionD' => '查清水情，确认安全后再通过',
    'answer' => '2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  86 => 
  array (
    'id' => 8357,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车准备通过漫水桥时，教练员应提示学员___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '即使是熟悉的桥面，其路况也难以预料',
    'optionB' => '轮胎与路面的附着力降低，容易打滑',
    'optionC' => '排气管位置较低，容易进水',
    'optionD' => '电器设备易受潮和短路',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  87 => 
  array (
    'id' => 8358,
    'typeId' => '15',
    'type' => 2,
    'subject' => '汽车准备驶入高速公路时，正确的驾驶方法是___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '在加速车道迅速加速到60km/h以上',
    'optionB' => '提前打开转向灯',
    'optionC' => '观察交通标志，选择正确的入口',
    'optionD' => '利用后视镜观察交通情况',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  88 => 
  array (
    'id' => 8359,
    'typeId' => '15',
    'type' => 2,
    'subject' => '进入山区道路行驶前，教练员应提示学员做好充分准备，主要包括___。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '保证充足的睡眠',
    'optionB' => '检查汽车技术状况',
    'optionC' => '检查汽车的装载情况',
    'optionD' => '检查随车工具、警告标志等',
    'answer' => '1,2,3,4',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  89 => 
  array (
    'id' => 8411,
    'typeId' => '15',
    'type' => 0,
    'subject' => '在道路上从事校车业务严重超员超速的构成危险驾驶罪将处拘役并处罚金。',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => '',
    'optionD' => '',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  90 => 
  array (
    'id' => 8427,
    'typeId' => '15',
    'type' => 1,
    'subject' => '客运车辆驾驶人24小时内累计驾驶时间不应超过多少小时？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '12',
    'optionB' => '10',
    'optionC' => '8',
    'optionD' => '6',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '《道路旅客运输企业安全管理规范》第四十五条：驾驶人在24小时内累计驾驶不得超过8小时，连续驾驶时间不得超过4小时，每次停车休息时间不少于20分钟。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
);