<?php return array (
  0 => 
  array (
    'id' => 6581,
    'typeId' => '9',
    'type' => 0,
    'subject' => '因交通事故造成有害气体泄漏后，进入现场抢救伤员时，抢救人员须佩戴空气呼吸器或用湿毛巾捂住口鼻。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《职业道德与安全行车知识》说明：因交通事故造成有害气体泄漏后，进入现场抢救伤员时，抢救人员须佩戴空气呼吸器或用湿毛巾捂住口鼻。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  1 => 
  array (
    'id' => 6582,
    'typeId' => '9',
    'type' => 0,
    'subject' => '在交通事故现场，一旦遇到有毒有害物质泄漏，一定要第一时间疏散人员，并立即报警。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '《职业道德与安全行车知识》说明：在交通事故现场，一旦遇到有毒有害物质泄漏，一定要第一时间疏散人员，并立即报警。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  2 => 
  array (
    'id' => 6583,
    'typeId' => '9',
    'type' => 1,
    'subject' => '交通事故中急救中毒伤员，以下做法错误的是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '尽快将中毒人员移出毒区',
    'optionB' => '脱去接触有毒空气的衣服',
    'optionC' => '用清水清洗暴露部位',
    'optionD' => '原地等待救援',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '交通事故中急救中毒伤员，需要：尽快将中毒人员移出毒区；脱去接触有毒空气的衣服；用清水清洗暴露部位。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  3 => 
  array (
    'id' => 6584,
    'typeId' => '9',
    'type' => 0,
    'subject' => '抢救有害气体中毒伤员时，应第一时间将伤员移送到有新鲜空气的地方，脱离危险环境，防止吸入更多有害气体。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '中毒伤员所处的空间肯定空气不流通，空气新鲜的地方可以让人体的呼吸管道起畅通的作用。因此应当先转移位置到空气新鲜的地方。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  4 => 
  array (
    'id' => 6585,
    'typeId' => '9',
    'type' => 0,
    'subject' => '驾驶机动车遇车辆出现燃烧现象，应迅速离开车内，以免对呼吸道造成伤害或发生窒息。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '驾驶机动车遇车辆出现燃烧现象，应迅速离开车内，以免对呼吸道造成伤害或发生窒息。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  5 => 
  array (
    'id' => 6586,
    'typeId' => '9',
    'type' => 0,
    'subject' => '驾驶机动车发生交通事故后，应注意是否有燃油泄漏、管路破裂的情况，避免意外情况出现。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '驾驶机动车发生交通事故后，应注意是否有燃油泄漏、管路破裂的情况，避免意外情况出现。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  6 => 
  array (
    'id' => 6587,
    'typeId' => '9',
    'type' => 0,
    'subject' => '道路危险货物运输驾驶人、装卸人员和押运员必须了解所运载的危险化学品的性质、危害特性、包装容器的使用特性和发生意外时的应急措施。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '根据《道路运输从业人员管理规定》第十二条道路危险货物运输装卸管理人员和押运人员应当符合下列条件：（三）接受相关法规、安全知识、专业技术、职业卫生防护和应急救援知识的培训，了解危险货物性质、危害特征、包装容器的使用特性和发生意外时的应急措施；因此本题是对的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  7 => 
  array (
    'id' => 6588,
    'typeId' => '9',
    'type' => 1,
    'subject' => '液化石油气罐车在运输途中发生大量泄漏时，下列措施错误的是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '切断一切电源',
    'optionB' => '戴好防护面具和手套',
    'optionC' => '关闭阀门制止渗漏',
    'optionD' => '组织人员向下风方向疏散',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '为了防止泄漏事件造成更大的伤害和损失，因此采取的措施应该是戴好防护面具和手套、切断一切电源、关闭阀门制止渗漏，并组织人员向上风方向疏散。而本题考的是错误的措施，如此一来，只有选项D是错误的。不是往下风方向，而是应当往上风方向。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  8 => 
  array (
    'id' => 6589,
    'typeId' => '9',
    'type' => 0,
    'subject' => '扑救易散发腐蚀性蒸气或有毒气体的火灾时，扑救人员应穿戴防毒面具和相应的防护用品，站在上风处施救。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '由于是“易散发腐蚀性蒸气或有毒气体的火灾”，因此既要做到不中毒，也要做到不被烫伤等，因此在扑救时，要穿戴防毒面具和相应的防护用品，这是为了防止中毒，而站在上风处施救，是因为不会因火势被伤到。因此本题是对的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  9 => 
  array (
    'id' => 6590,
    'typeId' => '9',
    'type' => 0,
    'subject' => '危险化学品具有爆炸、易燃、毒害、腐蚀、放射性等特性。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '危险化学品是指具有毒害、腐蚀、爆炸、燃烧、助燃等性质，对人体、设施、环境具有危害的剧毒化学品和其他化学品。因此本题正确。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  10 => 
  array (
    'id' => 6591,
    'typeId' => '9',
    'type' => 0,
    'subject' => '腐蚀品着火时，不能用水柱直接喷射扑救。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '无机腐蚀品或有机腐蚀品直接燃烧时，除具有与水反应特性的物质外，一般可用大量的水扑救。但宜用雾状水，不能用高压水柱直接喷射物品，以免飞溅的水珠带上腐蚀品灼伤灭火人员。液体腐蚀品应用干砂、干土覆盖吸收，扫干净后，再用水洗刷。大量溢出时可用稀酸或稀碱中和。中和时，要防止发生剧烈反应。用水洗刷撒漏现场时，只能缓慢地浇洗或用雾状水喷淋，以防水珠飞溅伤人。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  11 => 
  array (
    'id' => 6592,
    'typeId' => '9',
    'type' => 0,
    'subject' => '易燃液体一旦发生火灾，要及时用水扑救。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '着火时，人们往往立即想到的是用水来灭，但有些火灾却是不能用水来扑救的。如果易燃液体密度比水小，就不应该用水，因为易燃液体会浮在水面继续燃烧。所以本题错误。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  12 => 
  array (
    'id' => 6593,
    'typeId' => '9',
    'type' => 1,
    'subject' => '下列属于危险易燃固体的是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '火柴',
    'optionB' => '火药',
    'optionC' => '电石',
    'optionD' => '炸药',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '只有火柴是易燃固体，其他选项属于易燃易爆固体。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  13 => 
  array (
    'id' => 6594,
    'typeId' => '9',
    'type' => 1,
    'subject' => '火柴、硫黄和赤磷属于哪类危险化学品？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '爆炸品',
    'optionB' => '氧化性物质',
    'optionC' => '自燃物品',
    'optionD' => '易燃固体',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '易燃固体是指在常温下以固态形式存在，燃点较低，遇火受热、撞击、摩擦或接触氧化剂能引起燃烧的物质。这三类物质正好符合，因此选“易燃固体”。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  14 => 
  array (
    'id' => 6595,
    'typeId' => '9',
    'type' => 1,
    'subject' => '火药、炸药和起爆药属于哪类危险化学品？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '氧化性物质',
    'optionB' => '易燃固体',
    'optionC' => '爆炸品',
    'optionD' => '自燃物品',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '氧化性物质是指在有氧气的环境下会被氧化，发生化学反应，很明显这三类物质在空气中不会自己变化，所以不选“氧化性物质”。自燃物品肯定不准确，三类物质都是不会无缘无故自己燃烧的，所以不选“自燃物品”。虽然这三类都很危险，但是并不易燃，都需要明火，只要需要明火点燃的都不是易燃物品，所以不选“易燃固体”。即本题应选“爆炸品”。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  15 => 
  array (
    'id' => 6596,
    'typeId' => '9',
    'type' => 0,
    'subject' => '伤员骨折处出血时，先固定好肢体再进行止血和包扎。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '伤员骨折处出血时，应先止血和消毒，然后再固定。因此本题错误。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  16 => 
  array (
    'id' => 6597,
    'typeId' => '9',
    'type' => 0,
    'subject' => '对无骨端外露的骨折伤员肢体固定时，要超过伤口上下关节。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '为什么要超过伤口上下关节呢？这是因为不能让这两个关节活动。这样做能防止骨折端的移位，防止造成血管和神经的损伤，后者的损伤是比较头疼的，比单纯的骨折要麻烦多了，尤其是神经的损伤，很可能会造成感觉或运动方面障碍；此外，防止骨折断端戳破皮肤从而造成骨折端的污染影响愈合。因此本题正确。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  17 => 
  array (
    'id' => 6598,
    'typeId' => '9',
    'type' => 0,
    'subject' => '伤员大腿、小腿和脊椎骨折时，一般不要随便移动伤者。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '应该是原地固定等待专业救护人员，脊柱骨折被移动很有可能将导致高位截瘫。所以本题正确。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  18 => 
  array (
    'id' => 6599,
    'typeId' => '9',
    'type' => 0,
    'subject' => '移动脊柱骨折的伤员，切勿扶持伤者走动，可用软担架运送。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '注意担架会引起误解，脊柱骨折意味着柔软的脊髓面临机械损伤（哪怕是非常微小的震动）所以必须保持脊柱固定（软担架根本不能规避机械损伤），所以，用软担架运送也是错误的！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  19 => 
  array (
    'id' => 6600,
    'typeId' => '9',
    'type' => 0,
    'subject' => '伤员骨折处出血时，要先固定，然后止血和包扎伤口。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '伤员骨折处出血时，应先止血和消毒，然后再固定。因此本题错误。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  20 => 
  array (
    'id' => 6601,
    'typeId' => '9',
    'type' => 1,
    'subject' => '怎样抢救脊柱骨折的伤员？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '采取保暖措施',
    'optionB' => '用软板担架运送',
    'optionC' => '用三角巾固定',
    'optionD' => '扶持伤者移动',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '应该是原地固定等待专业救护人员，脊柱骨折被移动很有可能将导致高位截瘫。所以本题唯一可以选的就是“用三角巾固定”了！',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  21 => 
  array (
    'id' => 6602,
    'typeId' => '9',
    'type' => 1,
    'subject' => '抢救骨折伤员时注意什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '迅速抬上担架送往医院',
    'optionB' => '适当调整损伤时的姿势',
    'optionC' => '用绷带对骨折部位进行包扎',
    'optionD' => '不要移动身体骨折部位',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '面对骨折伤员，抢救时一定要确保不会造成二次伤害，即不能让骨折情况变严重或恶化，因此除了“不要移动身体骨折部位”之外，其他选项都有可能造成二次伤害。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  22 => 
  array (
    'id' => 6603,
    'typeId' => '9',
    'type' => 0,
    'subject' => '为防止有害气体中毒伤员继续中毒，首先将伤员转移到空气新鲜的地方。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '中毒伤员所处的空间肯定空气不流通，空气新鲜的地方可以让人体的呼吸管道起畅通的作用。因此应当先转移位置到空气新鲜的地方。因此本题正确。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  23 => 
  array (
    'id' => 6604,
    'typeId' => '9',
    'type' => 1,
    'subject' => '救助有害气体中毒伤员，首先采取的措施是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '采取保暖措施',
    'optionB' => '将伤员转移到有新鲜空气的地方',
    'optionC' => '进行人工呼吸',
    'optionD' => '进行胸外心脏按压',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '中毒伤员所处的空间肯定空气不流通，空气新鲜的地方可以让人体的呼吸管道起畅通的作用。因此应当先转移位置到空气新鲜的地方。只有在将中毒伤员转移至空气新鲜的地方之后，才能做其他措施。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  24 => 
  array (
    'id' => 6605,
    'typeId' => '9',
    'type' => 0,
    'subject' => '救助全身燃烧伤员可以采取向身上喷冷水灭火的措施。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '这是因为用冷水喷上去除了能够给创面降温以外，还能清洁伤口。因此本题正确。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  25 => 
  array (
    'id' => 6606,
    'typeId' => '9',
    'type' => 0,
    'subject' => '烧伤伤员口渴时，只能喝白开水。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '烧伤有创面，会损失体液，淡盐水可补充体液。至于为啥淡盐水可补充体液，因为人的体液本来也含盐，淡盐水可迅速补充。因此本题错误。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  26 => 
  array (
    'id' => 6607,
    'typeId' => '9',
    'type' => 0,
    'subject' => '烧伤伤员口渴时，可喝少量的淡盐水。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '烧伤有创面，会损失体液，淡盐水可补充体液。至于为啥淡盐水可补充体液，因为人的体液本来也含盐，淡盐水可迅速补充。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  27 => 
  array (
    'id' => 6608,
    'typeId' => '9',
    'type' => 1,
    'subject' => '救助全身燃烧伤员采取哪种应急措施？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '用沙土覆盖火焰灭火',
    'optionB' => '向身上喷冷水灭火',
    'optionC' => '用灭火器进行灭火',
    'optionD' => '帮助脱掉燃烧的衣服',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '先大家要明确，燃烧过后人体皮肤已经受损因此若是用A的方法，且不说沙土上附着的病原体会造成严重感染，事后的清理和后续治疗也会相当麻烦。而选项B，除了能够给创面降温以外，还有可能是清洁伤口，救治时限可以放宽到12小时。而选项C，则很有可能灭火器喷出的东西会造成身体上的伤害，因此不妥当。选项D，应该是帮助脱去未燃烧的衣服。因此本题选“向身上喷冷水灭火”。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  28 => 
  array (
    'id' => 6609,
    'typeId' => '9',
    'type' => 0,
    'subject' => '救助失血过多出现休克的伤员要采取保暖措施。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '失血过多+休克的伤员；注意是休克，休克的意思是血压下降，口渴，体温下降，意识模糊，皮肤发白，尿量减少的一种状态。所以要采取保暖措施。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  29 => 
  array (
    'id' => 6610,
    'typeId' => '9',
    'type' => 0,
    'subject' => '在紧急情况下为伤员止血时，须先用压迫法止血后再根据出血情况改用其他止血法。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '一般小动脉和静脉出血可用加压包扎止血法，较大的动脉出血，应用止血带止血。但在紧急情况下，须先用压迫法止血，然后再根据出血情况改用其它止血法。指压止血法可以在较大的动脉出血后，用拇指压住出血的血管上方(近心端)，使血管被压闭住，中断血液。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  30 => 
  array (
    'id' => 6611,
    'typeId' => '9',
    'type' => 0,
    'subject' => '在没有绷带急救伤员的情况下，可用毛巾、手帕、床单、长筒尼龙袜子等代替绷带包扎。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '根据受伤位置的不同和创面的大小，你可以利用毛巾、手帕做成简易的三角巾，用于手臂骨折的固定等，长袜子可以作为固定捆绑的绳子。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  31 => 
  array (
    'id' => 6612,
    'typeId' => '9',
    'type' => 1,
    'subject' => '包扎止血不能用的物品是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '绷带',
    'optionB' => '三角巾',
    'optionC' => '止血带',
    'optionD' => '麻绳',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '包扎止血，要求包扎物表面平整而且松软，这样才能有效地扎紧受伤部位体内的血管，阻止血管内的血液再在流通，达到止血的目的。麻绳，一般说来总是比较粗的，是由几股细绳绞合而成的。其表面不是平整光滑的，也不够柔软。因此一般不适合用以止血包扎。有时，可见护士用纱布撕成条，再合并起来用以包扎止血，这是因为纱布比较柔软，合并后较粗一些，包扎效果更好。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  32 => 
  array (
    'id' => 6613,
    'typeId' => '9',
    'type' => 1,
    'subject' => '采用指压止血法为动脉出血伤员止血时，拇指压住伤口的什么位置？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '近心端动脉',
    'optionB' => '血管下方动脉',
    'optionC' => '远心端动脉',
    'optionD' => '血管中部',
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '近心端就是靠近心脏方向的一端。动脉血管中血液的流动依靠心脏搏动来完成，如果动脉血管出血，压迫近心端血管就可以降低心脏对血液的传递，达到减少出血的目的。因此“近心端动脉”是对的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  33 => 
  array (
    'id' => 6614,
    'typeId' => '9',
    'type' => 1,
    'subject' => '在没有绷带急救伤员的情况下，以下救护行为中错误的是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '用手帕包扎',
    'optionB' => '用毛巾包扎',
    'optionC' => '用棉质衣服包扎',
    'optionD' => '用细绳缠绕包扎',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '根据受伤位置的不同和创面的大小，可以利用毛巾、手帕做成简易的三角巾。细绳由于其表面不是平整光滑的，也不够柔软。因此不能用来包扎，而棉质衣服相对比较柔软，因此可以。题目问的错误选项是，因此是“用细绳缠绕包扎”。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  34 => 
  array (
    'id' => 6615,
    'typeId' => '9',
    'type' => 1,
    'subject' => '抢救失血伤员时，要先采取什么措施？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '观察',
    'optionB' => '包扎',
    'optionC' => '止血',
    'optionD' => '询问',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '既然是失血伤员，首先要做的当然是止血。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  35 => 
  array (
    'id' => 6616,
    'typeId' => '9',
    'type' => 0,
    'subject' => '抢救昏迷失去知觉的伤员要在抢救前先检查呼吸。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '检查呼吸的目的是为了了解伤员的生命体征，而这必须是要先确认的。因此本题正确。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  36 => 
  array (
    'id' => 6617,
    'typeId' => '9',
    'type' => 0,
    'subject' => '搬运昏迷失去知觉的伤员要采取仰卧位。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '正确的做法是先开放气道，再采取去枕仰卧位，头偏向一侧，保持呼吸道通畅，以防窒息。因此本题错误。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  37 => 
  array (
    'id' => 6618,
    'typeId' => '9',
    'type' => 1,
    'subject' => '抢救昏迷失去知觉的伤员需注意什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '马上实施心肺复苏',
    'optionB' => '使劲掐伤员的人中',
    'optionC' => '连续拍打伤员面部',
    'optionD' => '抢救前先检查呼吸',
    'answer' => '4',
    'optionSimple' => NULL,
    'solve' => '因为抢救前要先确认伤员的生命体征，只有确认了之后才能做出适当的抢救措施。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  38 => 
  array (
    'id' => 6619,
    'typeId' => '9',
    'type' => 0,
    'subject' => '受伤者在车内无法自行下车时，可设法将其从车内移出，尽量避免二次受伤。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '1',
    'optionSimple' => NULL,
    'solve' => '如题，受伤者既然无法自行下车，那肯定说明是行动不便的，若不设法将伤者从车内转移出来，万一车子发生什么状况，受伤者可能都无法及时躲避，这样很容易造成更大的伤害。因此这题是正确的。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  39 => 
  array (
    'id' => 6620,
    'typeId' => '9',
    'type' => 0,
    'subject' => '遇伤者被压于车轮或货物下时，要立即拉拽伤者的肢体将其拖出。',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '正确',
    'optionB' => '错误',
    'optionC' => NULL,
    'optionD' => NULL,
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '车轮压住了伤者，必须将车轮或货物移开后才能将伤者移出。如果硬拖的话，容易使伤者伤得更严重。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  40 => 
  array (
    'id' => 6621,
    'typeId' => '9',
    'type' => 1,
    'subject' => '在事故现场抢救伤员的基本要求是什么？',
    'subjectSimple' => NULL,
    'imgUrl' => NULL,
    'optionA' => '先治伤，后救命',
    'optionB' => '先救命，后治伤',
    'optionC' => '先帮助轻伤员',
    'optionD' => '后救助重伤员',
    'answer' => '2',
    'optionSimple' => NULL,
    'solve' => '必须先救人，否则很有可能因为送医不及时而造成伤者死亡。而受伤的人员没有生命危险，可以暂缓一下。因此要“先救命，后治伤”。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
  41 => 
  array (
    'id' => 8048,
    'typeId' => '9',
    'type' => 1,
    'subject' => '止血带止血是用弹性的橡皮管、橡皮带，上肢结扎于伤员上臂什么位置？',
    'subjectSimple' => NULL,
    'imgUrl' => '',
    'optionA' => '上四分之三',
    'optionB' => '上三分之二',
    'optionC' => '上三分之一',
    'optionD' => '上二分之一',
    'answer' => '3',
    'optionSimple' => NULL,
    'solve' => '橡皮止血带是一种特制的橡皮管，在现场可使用橡皮条、自行车内胎等替代。使用时要把止血带放在肢体适当的部位，如上肢要放在上臂中上1/3处；下肢放在大腿的中下1/3处。',
    'createTime' => NULL,
    'updateTime' => NULL,
    'typeCN' => NULL,
    'userDoQuestion' => 
    array (
      'id' => NULL,
      'userId' => NULL,
      'questionId' => NULL,
      'isError' => NULL,
      'isCollect' => NULL,
      'answer' => NULL,
      'createTime' => NULL,
      'updateTime' => NULL,
    ),
    'questionType' => NULL,
  ),
);