<?php

namespace app\api\controller\answer;

use app\api\controller\Controller;
use app\api\model\camera\Exam;
use app\api\model\CameraExam;
use app\api\model\Setting;
use app\common\library\AipOcr;
use think\Db;
use think\Request;

class Index extends Controller
{
    protected $user;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = $this->getUser(true);
        if ($this->user['card_type'] == 10 && $this->user["second"] == 0) {
            $this->throwError("搜题次数不足");
        } else if ($this->user['card_type'] != 10) {
            if (strtotime($this->user['end_time']) < time()) {
                ## 过期之后自动变回次数账户
                $this->user['card_type'] = 10;
                $this->user->save();
                $this->throwError("会员已过期");
            }
            if ($this->user["second"] <= 0) {
                $this->throwError("搜题次数不足");
            }
        }
    }

    ## 搜题
    public function search($keys)
    {
        if (is_url($keys)) {
            return $this->imageSearch($keys);
        }
        return $this->textSearch($keys);
    }

    ## 图片搜题
    public function imageSearch($image_url)
    {
        $ocr = Setting::getItem("ocr");
        $client = new AipOcr($ocr['app_id'], $ocr['api_key'], $ocr['secret_key']);
        if ($ocr["is_model"] == 10) {
            $result = $client->basicGeneralUrl($image_url);
        } else {
            $image = file_get_contents($image_url);
            $result = $client->basicAccurate($image);
        }
        if (!isset($result['words_result']) || !$result['words_result']) {
            return $this->renderError("未识别到任何内容");
        }
        if (!$result['words_result']) {
            return $this->renderError("未识别到内容");
        }
        $text = "";
        foreach ($result['words_result'] as $values) {
            $text .= $values['words'];
        }
        return $this->textSearch($text);
    }

    ## 文本搜索
    public function textSearch($text)
    {
        $ocr = Setting::getItem("ocr");
        if ($ocr['topic'] == 10) {
            $answer = $this->LocalCloud($text);
        } else {
            $answer = $this->longRangeCloud($text);
        }
        if (!$answer) {
            return $this->renderError("未识别到任何内容");
        }
        ## 扣次数
//        if ($this->user['card_type'] == 10) {
//        }
        $this->user->second = ['dec', 1];
        $this->user->save();
        return $this->renderSuccess(compact("answer"), "搜索成功");
    }

    ## 本地识别
    public function LocalCloud($text)
    {
        $sql = "SELECT *,MATCH (title,a,b,c,d,content) AGAINST ('" . $text . "' IN NATURAL LANGUAGE MODE) AS score
 FROM yoshop_camera_subject_img where MATCH (title,a,b,c,d,content) AGAINST ('" . $text . "' IN NATURAL LANGUAGE MODE) > 0 ORDER BY score DESC limit 5;";
        $result = Db::query($sql);
        if (!$result) {
            return false;
        }
        foreach ($result as $key => &$val) {
            $val["imgUrl"] = base_url() . "tiku_image/" . $val["imgUrl"];
        }
        return $result;
    }

    ## 云端识别
    public function longRangeCloud($text)
    {
        $sql = "SELECT *,MATCH (optionA,optionB,optionC,optionD,subject) AGAINST ('" . $text . "' IN NATURAL LANGUAGE MODE) AS score
 FROM yoshop_camera_question where MATCH (optionA,optionB,optionC,optionD,subject) AGAINST ('" . $text . "' IN NATURAL LANGUAGE MODE) > 0 ORDER BY score DESC limit 5;";
        $result = Db::query($sql);
        if (!$result) {
            return false;
        }
        $data = [];
        foreach ($result as $key => $val) {
            $answer = explode(",", $val["answer"]);
            $index[1] = "A";
            $index[2] = "B";
            $index[3] = "C";
            $index[4] = "D";
            $answer_txt = "";
            foreach ($answer as $k => $v) {
                $answer_txt .= $index[$v] . ",";
            }
            $answer_txt = rtrim($answer_txt, ",");
            $data[$key]['a'] = $val["optionA"];
            $data[$key]['b'] = $val["optionB"];
            $data[$key]['c'] = $val["optionC"];
            $data[$key]['d'] = $val["optionD"];
            $data[$key]['content'] = $val["solve"];
            $data[$key]['title'] = $val["subject"];
            $data[$key]['dn'] = $answer_txt;
            $data[$key]["imgUrl"] = $val["imgUrl"];
        }
        return $data;
    }
}